<a href="https://colab.research.google.com/github/ceydatekin/NumpyPandasKutuphaneleri/blob/main/GDSC_YAPAY_ZEKAYA_G%C4%B0R%C4%B0%C5%9E_E%C4%9E%C4%B0T%C4%B0M%C4%B0_NUMPY_K%C3%9CT%C3%9CPHANES%C4%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**VERİ MANİPÜLASYONU**

> Veri işleme, veri biliminin ayrılmaz bir yönüdür. Verilerin, makinelerin okuyabilmesi için yapılandırılması gerekir. Ancak, insanların onu kullanması için manipülasyona ihtiyacı var. Her geçen gün kullanılan veri miktarı ve depolama arttıkça, veri manipülasyonu her zamankinden daha kritik hale geliyor.

> Verileri manipüle farklı pek çok dilde edebilirsiniz ama aslında işin ana yapısını aynıdır. Sadece yazımsal değişikliğe uğrar.
>Biz **Python**'ın kütüphanelerinden olan *NumPy* ve *Pandas*'ı kullanacağız.




## NUMPY KÜTÜPHANESi

### Neden Numpy Kullanmalıyız

In [ ]:
array1 = [1,2,3,4]
array2 = [2,3,4,5]

In [ ]:
#iki listemizi çarpmak için karışık bir ifade kullanırız asağidaki gibi
carpım = []

for i in range (0,len(array1)):
    carpım.append(array1[i]*array2[i])

print(carpım)

[2, 6, 12, 20]


In [ ]:
#NumPy kütüphanesini programımıza cağırmadan kullanamayız.
#Aşağıdaki ifade de NumPy kütüphanesini np kısayolu ile programımıza dahil etmiş olduk.
import numpy as np

In [ ]:
#numpy arrayleri iki liste çarpımını kolaylaştırmak mümkündür asağıda inceleyiniz:
#önce iki np kısayolu ile numpy arrayi oluşturduk
arr1 = np.array([1,2,3,4])
arr2 = np.array([2,3,4,5])

In [ ]:
#oluşturduğumuz arrayleri çarpmak için aşağıdaki işlem yeterlidir.
arr1*arr2

array([ 2,  6, 12, 20])

### NumPy Arrayi Oluşturma İşlemleri

In [ ]:
arr = np.array([1,2,3,4,6])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 6]



> NumPy sabit tip baskında bir kütüphanedir.


In [ ]:
np.array([3.14, 4, 2, 13]) #Bir tanesi bile float tipine dönmüş olsa bile hepsi floata dönüşür.

array([ 3.14,  4.  ,  2.  , 13.  ])

In [ ]:
np.array([3.14, 4, 2, 13], dtype = "int") #dtype o arrayin türünü belirlememizi sağlar.

array([ 3,  4,  2, 13])

In [ ]:
#Verilen boyut kadar 0 elemanlı NumPy Arrayi oluşturur.
#Ve sayılarımızı "Float" tipinde oluşturur. 
arr1 = np.zeros(8)
arr2 = np.zeros((2,8), dtype = int)
print("Birinci Array")
print(arr1)
print("İkinci Array")
print(arr2)

Birinci Array
[0. 0. 0. 0. 0. 0. 0. 0.]
İkinci Array
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [ ]:
#Verilen boyut kadar 1 elemanlı NumPy Arrayi oluşturur.
arr1 = np.ones((3,5), dtype = int)
arr2 = np.ones(5)
print("Birinci Array")
print(arr1)
print("İkinci Array")
print(arr2)

Birinci Array
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
İkinci Array
[1. 1. 1. 1. 1.]


In [ ]:
#Verilen boyut kadar "parametre verilen sayı" elemanlı NumPy Arrayi oluşturur.
np.full((3,5), 3, dtype = int)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [ ]:
#Verilen aralık ve artış miktarına göre bir NumPy Arrayi oluşturur.
np.arange(40 ,0, -3)

array([40, 37, 34, 31, 28, 25, 22, 19, 16, 13, 10,  7,  4,  1])

In [ ]:
#Başlangıç, bitiş ve dizi boyutunu parametre olarak alır.
#np.linspace() metodu başlangıçtan sona num tane sayıyı birbiri arası uzaklık eşit olacak şekilde böler.
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [ ]:
#normal dağılıma uygun rastgele veriler oluşturup verilen boyutta NumPy Arrayi yapar.
np.random.normal(10,4,(3,3))

array([[14.32203304,  8.68651824, 13.53713972],
       [10.86088487,  5.56669364,  5.0403621 ],
       [ 7.17677136, 12.8723852 , -2.15239921]])

In [ ]:
#başlangıç ve bitiş aralığında boyut kadar random integer olarak eleman oluşturur.
np.random.randint(1,100,6)

array([42, 87, 47,  8,  5, 84])

In [ ]:
?np.zeros #Yardım istediğimizde  ?....... o fonksiyonun özelliğini detaylı öğreniriz.

### Numpy Array Özellikleri
* **ndim:** _boyut sayısı_
* **shape:** _boyut bilgisi_
* **size:** _toplam eleman sayısı_
* **dtype:** _array veri tipi_

In [ ]:
#İki tane random integerlardan oluşan bir array tanımlayalım.
arr1 = np.random.randint(20,size = 10)
arr2 = np.random.randint(20,size = (9,2))
print(arr1)
print(arr2)

[18 10 11  8 18  5  8  1  8  6]
[[ 0 13]
 [13  5]
 [ 2 18]
 [ 1 17]
 [ 5  5]
 [19  7]
 [ 2 14]
 [ 6 16]
 [ 1  4]]


In [ ]:
print("Birinci Arrayin Boyut Sayısı")
print(arr1.ndim)
print("İkinci Arrayin Boyut Sayısı")
print(arr2.ndim)

Birinci Arrayin Boyut Sayısı
1
İkinci Arrayin Boyut Sayısı
2


In [ ]:
print("Birinci Arrayin Boyut Bilgisi")
print(arr1.shape)
print("İkinci Arrayin Boyut Bilgisi")
print(arr2.shape)

Birinci Arrayin Boyut Bilgisi
(10,)
İkinci Arrayin Boyut Bilgisi
(9, 2)


In [ ]:
print("Birinci Arrayin Eleman Sayısı")
print(arr1.size)
print("İkinci Arrayin Eleman Sayısı")
print(arr2.size)

Birinci Arrayin Eleman Sayısı
10
İkinci Arrayin Eleman Sayısı
18


In [ ]:
print("Birinci Arrayin Veri Tipi")
print(arr1.dtype)
print("İkinci Arrayin Veri Tipi")
print(arr2.dtype)

Birinci Arrayin Veri Tipi
int64
İkinci Arrayin Veri Tipi
int64


### Yeniden Şekillendirme (Reshaping)
.reshape(boyut)

In [ ]:
arr1 = np.arange(1,10) #1'den 10 kadar 9 elemanlı :)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Biz bu arrayi (3,3) boyutlu bir diziye cevirmek için
print(np.arange(1,10).reshape((3,3)))
print(arr1.reshape((3,3)))
print(arr1) #ÖNEMLİ : Gerçek arrayde bir kaydetme olmadığı için arrayimiz değişmedi

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [ ]:
arr1 = arr1.reshape((3,3)) 
print(arr1) #yaptığımız değişikliği kaydettiğimiz için üstüne arrayimiz güncellendi

[[1 2 3]
 [4 5 6]
 [7 8 9]]




> Basit bir noktaya değinmek istiyorum çif boyutlu yani **.ndim** çağrıldığında sonucu iki ve üstü olan her şey matris, sonucu 1 olan her şeye vektör denir.


> (1,sayi) boyutu vektör gibi görünsede aslına bir matristir unutmayınız :)




 ### Birleştirme (Concantenation)
 .concatenate( [ arr1, arr2, arr3 ], axis = 0 - 1)


*   axis = 0 => satır bazlı birleştirir
*   axis = 1 =>  sütun bazlı birleştirir



#### Tek Boyutta Birleştirme

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y])
z = np.array([4,5,6])

In [ ]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 4, 5, 6])

#### Çift Boyutta Birleştirme

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])

In [ ]:
np.concatenate([a,a]) #axis belirtilmediğin default değeri alınır
                      # default değeri 0'dır. Aşağıya doğru birleştirir.
#np.concatenate([a,a], axis = 0) da yazılabilmektedir.

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([a,a], axis = 1) #Yana doğru birleştirilir.

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### Array Ayırma (Splitting)
.split(array, [ayrılacak dizi indislerinin sayısı] )

> ÖNEMLİ : yazılan indis dahil edilmez.
#### Tek Boyutta Ayırma



In [ ]:
x = np.array([1,2,3,99,99,3,2,1])

In [ ]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

* .split icindeki sayilar 0 dan 3 e kadar ayırır 3 den 5 e kadar ve 5 den sonuna kadar
* Bu arraylaribir değere atayıp kullanabilmek içinse kaç parçaya bölünecekse o kadar değere atamalıyız.


In [ ]:
x = np.array([1,2,3,99,99,3,2,1,100,5])
a,b,c,d = np.split(x, [2,4,6])
print(a, b, c, d)
d

[1 2] [ 3 99] [99  3] [  2   1 100   5]


array([  2,   1, 100,   5])

#### Çok Boyutta Ayırma

In [ ]:
arr1 = np.arange(16).reshape(4,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])


> Çok boyutta ayırma işleminin farkı sütun yada satır bazında ayrılabileceği için iki farklı durum söz konusudur. Biz bu sebeple iki fonksiyon kullanırız. Bunlar:


*   **.hsplit** => sütun olarak böler ve sonuc yan yana olur yani yatay
*   **.vsplit** => satır olarak böler sonuc dikey olur 







In [ ]:
np.vsplit(arr1, [3])

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]

In [ ]:
#Bunlarıda daha sonra kullanabilmek için bir değerlere atabiliriz. 
ust, alt = np.vsplit(arr1, [2])
print("üst arrayimiz")
print(ust)
print("alt arrayimiz")
print(alt)

üst arrayimiz
[[0 1 2 3]
 [4 5 6 7]]
alt arrayimiz
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
np.hsplit(arr1, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
sag, sol = np.hsplit(arr1, [3])
print("sag arrayimiz")
print(sag)
print("sol arrayimiz")
print(sol)

sag arrayimiz
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
sol arrayimiz
[[ 3]
 [ 7]
 [11]
 [15]]


### Sıralama (Sorting)
.sort

In [ ]:
arr1 = np.array([9,5,6,7,1,8,4])

In [ ]:
np.sort(arr1) #arrayimiz küçükten büyüğe doğru sıralandı

array([1, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1 #ama gördüğünüz üzere ana arrayde herheangi bir değişiklik mevcut değildir

array([9, 5, 6, 7, 1, 8, 4])

In [ ]:
arr1.sort() #arrayimiz küçükten büyüğe doğru sıralandı

In [ ]:
arr1 #ana array üzerinde bir değişiklik mevcuttur

array([1, 4, 5, 6, 7, 8, 9])

* np kutuphanesinden .sort(array) yapınca arrayin kendi hali bozulmaz.
* array.sort() yapınca ise arrayin kendsisi siralandi yapisi bozuldu.

In [ ]:
arr2 = np.random.normal(20,5, (3,3))
arr2

array([[23.68375481, 15.12312126, 23.32426463],
       [ 8.40872614, 17.37938509, 28.66197474],
       [17.30347636, 12.93412292, 15.53565436]])

In [ ]:
np.sort(arr2, axis = 1) #aslında sütun sütun bakılıp satırlar sıralanmış olur.

array([[15.12312126, 23.32426463, 23.68375481],
       [ 8.40872614, 17.37938509, 28.66197474],
       [12.93412292, 15.53565436, 17.30347636]])

In [ ]:
np.sort(arr2, axis = 0) #aslında satır satır bakılıp sütunlar sıralanmış olur.

array([[ 8.40872614, 12.93412292, 15.53565436],
       [17.30347636, 15.12312126, 23.32426463],
       [23.68375481, 17.37938509, 28.66197474]])

### Eleman İşlemleri


*   İndeksleme Yöntemi
* Slicing Yöntemi 
*   Fancy Yöntemi


####İndeks İle Elemanlara Erişmek

In [ ]:
a=np.random.randint(10, size=12)
a

array([7, 1, 7, 0, 9, 6, 0, 9, 1, 9, 1, 0])

In [ ]:
a[0]
print(a)
print(a[0], a[-2])

[1 2 6 1 2 2 7 7 0 4 6 4]
1 6


In [ ]:
a[0]=100
a

array([100,   2,   6,   1,   2,   2,   7,   7,   0,   4,   6,   4])

In [ ]:
m = a.reshape((4,3))
m

array([[7, 1, 7],
       [0, 9, 6],
       [0, 9, 1],
       [9, 1, 0]])

In [ ]:
print(m[1,2]) # m[satır_indisi , sütun_indisi]
print(m[2,1]) 

6
9


### Array Alt Küme İşlemleri
Slicing ile Elemanlara Erişmek 

Tek Boyutta Slicing

In [ ]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
a[0:3] #0. indeksten 3. indekse kadar olan elemanlar

array([20, 21, 22])

In [ ]:
a[:3] #0 yazılmayadabilir böyle durumda baştan başlar.

array([20, 21, 22])

In [ ]:
a[3:] #belirtilen indeksten başlayıp sonuncu indekse kadar alır

array([23, 24, 25, 26, 27, 28, 29])

In [ ]:
a[1::2] #1. indeksten başlayıp sonuncu indekse kadar indeks sayısını ikişer ikişer arttırır.

array([21, 23, 25, 27, 29])

İki Boyutta Slicing

[satır , sütün]

In [ ]:
m = np.random.randint(10, size=(5,5))
m

array([[9, 1, 8, 3, 8],
       [3, 9, 6, 7, 0],
       [1, 4, 7, 9, 2],
       [0, 1, 3, 0, 9],
       [6, 0, 0, 0, 7]])

In [ ]:
m[:,0] #satırın tamami 0. indeksli sütun

array([9, 3, 1, 0, 6])

In [ ]:
m[:,3] #satırın tamami 3. indeksli sütun

array([3, 7, 9, 0, 0])

In [ ]:
m[0,:] #sütunun tamami 0. indeksli satır

array([9, 1, 8, 3, 8])

In [ ]:
m[0,:2] # 0. indeksli satır ve 0.indeksten 2.indekse kadar olan sütun

array([9, 1])

In [ ]:
m[0:2 , 0:3] #?

array([[9, 1, 8],
       [3, 9, 6]])

In [ ]:
m[:: , 0:2]  # :: işareti : bu işaretle aynı anlama gelir yani tamamı anlamına

array([[9, 1],
       [3, 9],
       [1, 4],
       [0, 1],
       [6, 0]])

In [ ]:
m[: , :2] 

array([[9, 1],
       [3, 9],
       [1, 4],
       [0, 1],
       [6, 0]])

In [ ]:
m[1:3 , 0:2]

array([[3, 9],
       [1, 4]])

In [ ]:
print(m)
print(m[:,0])
print(m[0:3, 0:2])
print(m[:: , 0:2]) #m[: , :2]  aynı anlama gelir
print(m[0,:]) #Sadece 0. indeksteki satırı seçer.
print(m[:,3]) #Sadece 3. indeksteki sütunu seçer.

[[9 1 8 3 8]
 [3 9 6 7 0]
 [1 4 7 9 2]
 [0 1 3 0 9]
 [6 0 0 0 7]]
[9 3 1 0 6]
[[9 1]
 [3 9]
 [1 4]]
[[9 1]
 [3 9]
 [1 4]
 [0 1]
 [6 0]]
[9 1 8 3 8]
[3 7 9 0 0]


### Alt Küme Üzerinde İslem Yapmak

In [ ]:
a= np.random.randint(10, size=(5,5))
a

array([[6, 4, 5, 4, 2],
       [4, 8, 4, 9, 1],
       [2, 0, 0, 4, 3],
       [8, 7, 8, 6, 3],
       [6, 6, 0, 2, 6]])

In [ ]:
alt_a= a[0:3, 0:2]    #slicing de yani ayirmada [a:b , c:d] de a:b kısmı satir c:d kısmı sutundur.
alt_a

array([[6, 4],
       [4, 8],
       [2, 0]])

In [ ]:
alt_a[0,0]=159
alt_a[1,1]=8888

In [ ]:
print("alt kümemiz yeni")
print(alt_a)
print("ana kümemiz yeni")
print(a)

alt kümemiz yeni
[[ 159    4]
 [   4 8888]
 [   2    0]]
ana kümemiz yeni
[[ 159    4    5    4    2]
 [   4 8888    4    9    1]
 [   2    0    0    4    3]
 [   8    7    8    6    3]
 [   6    6    0    2    6]]



> Bir numpy arrayini slicing islemi ile ayirip bir degiskene atanirsa ve o ayrilan arrayde bir degisiklik yapilirsa ana array degisir.



In [ ]:
m= np.random.randint(10, size=(5,5))
m

array([[9, 7, 9, 3, 4],
       [3, 2, 0, 3, 4],
       [1, 6, 6, 6, 7],
       [4, 8, 5, 1, 0],
       [0, 1, 4, 0, 6]])



> **.copy()** metodu ile arrayin parçasinin kopyasi alinir ve ana array degismez



In [ ]:
alt_b= m[0:3 , 0:2].copy()
alt_b 

array([[9, 1],
       [3, 9],
       [1, 4]])

In [ ]:
alt_b[0,0]=78954
alt_b 

array([[78954,     1],
       [    3,     9],
       [    1,     4]])

In [ ]:
print("alt kümemiz yeni")
print(alt_b)
print("ana kümemiz yeni")
print(m)

alt kümemiz yeni
[[78954     1]
 [    3     9]
 [    1     4]]
ana kümemiz yeni
[[9 1 8 3 8]
 [3 9 6 7 0]
 [1 4 7 9 2]
 [0 1 3 0 9]
 [6 0 0 0 7]]


### Fancy Index İle Elemanlara Erişmek

>Fancy yöntemi basit index yöntemi gibi olsada bir np arrayinden bir anda bir liste veya np arrayindeki yazan elemanların gösterimine yarar






In [ ]:
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
#biz 1,3 ve 5. indeksleri almak istersek bu arrayden indekleseme yöntemiyle
[v[1], v[3], v[5]] #bunu yazmamız gerekir

[3, 9, 15]

In [ ]:
#Fancy yönteminde ise bir liste oluşturulup indeks gibi yazılınca 
#liste içindeki yazan değerlerdeki indeksleri getirir. :)
al_getir = [1,3,5]
v[al_getir]

array([ 3,  9, 15])

In [ ]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#Hem numpy arrayi hem normal liste kullanılabilinir 
satir = np.array([0,1])
print("satir:")
print(satir)
sutun = [1,2]
print("sütun:")
print(sutun)

satir:
[0 1]
sütun:
[1, 2]


In [ ]:
m[satir, sutun]

array([1, 6])

In [ ]:
m[0, [0,1,2]] # 0, [684646] gibi ifadede 0 dan sonrasını göstren : işareti olmadığından basit index 

array([9, 1, 8])

In [ ]:
m[0: , [0,1,2]]  # 0, [684646] gibi ifadede 0 dan sonrasını göstren : işareti olmadığından slicing işlemi

array([[9, 1, 8],
       [3, 9, 6],
       [1, 4, 7],
       [0, 1, 3],
       [6, 0, 0]])

##Koşullu Eleman İşlemleri

In [ ]:
v= np.array([1, 2, 3, 4, 5])
v

array([1, 2, 3, 4, 5])

In [ ]:
v>5

array([False, False, False, False, False])

In [ ]:
v<3

array([ True,  True, False, False, False])

In [ ]:
k= np.array([1, 2, 3, 4, 5,7]).reshape([2,3])

In [ ]:
k<2

array([[ True, False, False],
       [False, False, False]])

In [ ]:
v[v<3] #fancy yontemi ile direk 3 den küçük olan değerleri döndürür

array([1, 2])

In [ ]:
v[v==3]

array([3])

In [ ]:
v[v!=3]

array([1, 2, 4, 5])

In [ ]:
v*15

array([15, 30, 45, 60, 75])

In [ ]:
v**2

array([ 1,  4,  9, 16, 25])

### Matematiksel işlemler

> Az önceki gibi dizi(dört işlem operatörleri)değer şeklindede yapabilsekde bu operatörlere yarayan bazı fonksiyonlar mevcuttur. 

In [ ]:
v = np.array([1, 2, 3, 4, 5]) 

In [ ]:
np.subtract(v,1) #- operatoru

array([0, 1, 2, 3, 4])

In [ ]:
np.add(v,1) #+operatoru

array([2, 3, 4, 5, 6])

In [ ]:
np.multiply(v,4) #* operatoru

array([ 4,  8, 12, 16, 20])

In [ ]:
np.divide(v, 3) #/ operatoru

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [ ]:
np.power(v,3) #** operatoru

array([  1,   8,  27,  64, 125], dtype=int32)

In [ ]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [ ]:
np.absolute(np.array([-3])) #mutlak deger fonk

array([3])

In [ ]:
np.sin(360)

0.9589157234143065

In [ ]:
np.cos(180)

-0.5984600690578581

In [ ]:
v = np.array([1,2,3])
np.log(v) #doğal logaritma e üssü :)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [ ]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

* np.mean(arr,axis=0) | Returns mean along specific axis
* arr.sum() | Returns sum of arr
* arr.min() | Returns minimum value of arr
* arr.max(axis=0) | Returns maximum value of specific axis
* np.var(arr) | Returns the variance of array
* np.std(arr,axis=1) | Returns the standard deviation of specific axis
* arr.corrcoef() | Returns correlation coefficient of array

In [ ]:
np.mean(v, axis=0) 

3.0

In [ ]:
v.sum() 

15

In [ ]:
v.min()

1

In [ ]:
v.max(axis=0) 

5

In [ ]:
np.var(v)

2.0

In [ ]:
np.std(v)

1.4142135623730951

In [ ]:
np.median(v)

3.0